<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  2 => 
  array (
    'package' => 'mail',
    'name' => 'mail',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/mail',
    'active' => false,
  ),
);
